### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Killako** [jcarbelbide/tog-crowdsourcing#18]
Hey, not sure why, but it seems like the website is down.

**Comment by Killako** [comment]
Thanks!

**Comment by jcarbelbide** [comment]
Thanks for reporting! Typically I try to respond within 5 minutes of the site being down unless I'm asleep. Unfortunately, this time, I had very spotty internet. I'm working on ways to try to stop this from happening in the first place. We're running into scaling issues it seems.
