### ISSUE TITLE
Website down, causing Runlite app to stop working

### ISSUE THREAD

**Issue by Viperruels** [jcarbelbide/tog-crowdsourcing#19]
Website down, causing Runlite app to stop working

**Comment by Viperruels** [comment]
310 is gggbbb currently if anyone needs it

**Comment by jcarbelbide** [comment]
We are having ongoing scaling issues due to high usage of the plugin. I'm looking into ways to mitigate this, but this is just a side project for me, so it's a bit hard to find time. The incident was resolved, so I'm closing this issue.
