### ISSUE TITLE
No world data being displayed

### ISSUE THREAD

**Issue by BulbagardenTech** [jcarbelbide/tog-crowdsourcing#20]
The interface is not currently displaying any world data, even if you stand at ToG and watch the streams.
![image](https://github.com/jcarbelbide/tog-crowdsourcing/assets/74686640/f92c698f-aafc-455c-9c93-533ad67d4f88)

**Comment by jcarbelbide** [comment]
ongoing issue, sorry about this. currently working on it. im not sure I can completely solve the issue without throwing more money at it (server is not too strong), but I will try.
