### ISSUE TITLE
Why does the plugin need my IP for submissions?

### ISSUE THREAD

**Issue by zahti** [jcarbelbide/tog-crowdsourcing#3]
Just curious.

**Comment by jcarbelbide** [comment]
Great question! I have [write up](https://github.com/jcarbelbide/togcrowdsourcing.com) I made (for fun mostly) in my repo for the website version of this plugin. It has to do with rate-limiting, since the API is exposed to anyone, and anyone can skew the tears data if they really wanted to. 

Here's a snippet from that:

>One more thing we want to collect is whether a user has already submitted a stream order or not. This is mostly to stop malicious POST requests that serve only to skew the data. For example, we do not want to allow someone using Postman to constantly send false data to our server, making it think that it is receiving a high number of requests for a particular stream order + world number combination. If it did, our database would accumulate a large number of hits for false data, and direct real users to the world with false data, leading to a bad user experience. We cannot stop malicious requests to our server, but we can certainly try to mitigate the extent to which they can skew the data.

>How do we identify unique users and stop them from sending too much false data? I did not want to have to have users create an account and password to use this plugin, because it would have been a hassle for the user. That means the best identifying piece of data would be the user's IP address. We could store the user's IP address along with the world number for which they are sending data, and block any subsequent requests from that user for that world. This makes it a bit harder for someone to skew the data on our server, but does not hamper the experience of real users.

>I know RuneScape users are very cautious when it comes to their IP address (for good reason), so I wanted to be very careful about how I use and store their IPs. I talk about this topic a bit more in the section below that addresses the question, "How do we protect the user's privacy?".

**Comment by jcarbelbide** [comment]
Also, technically any time you use something over the internet, the service will see your IP

**Comment by jcarbelbide** [comment]
Closing as there are no further questions, but please feel free to reopen if there are more :)
